### ISSUE TITLE
Warning if CLI outdated

### ISSUE THREAD

**Issue by pkbullock** [ValoIntranet/doctor#10]
I just tried running this, but using an outdated CLI, see example, ok this is probably low hanging fruit but if there is a dependency on a version, the tool could check for this..

![image](https://user-images.githubusercontent.com/8781041/102469883-31f81980-404b-11eb-818b-5296c70fbae6.png)

**Comment by estruyf** [comment]
The tool uses its own version of the CLI for Microsoft just for these reasons. That is why you see `localm365` in there.

**Comment by estruyf** [comment]
Looking into this error, it could be related to Windows which hasn't been tested yet as the tool only ran on macOS and Linux agents. This is something on the enhancement list.

**Comment by estruyf** [comment]
Should have been fixed in version `1.2.0`. If not, feel free to open this issue or a new one.
