### ISSUE TITLE
I blew it up trying to run help

### ISSUE THREAD

**Issue by pkbullock** [ValoIntranet/doctor#11]
I tried a command that wasn't supported which wasn't handled well

![image](https://user-images.githubusercontent.com/8781041/102470163-89968500-404b-11eb-97ab-5c944b8d59c6.png)

PS. Just found the usage info on the homepage of the repo, so will follow that from now on lol

**Comment by estruyf** [comment]
WHAT! No help! The docs can help you! But this should indeed be included. Thanks for opening this issue.

**Comment by estruyf** [comment]
Included a fix for this and will be released with the next version.

![Screenshot 2020-12-17 at 12 05 18](https://user-images.githubusercontent.com/2900833/102480138-27944a80-4060-11eb-8f11-b03ac437eea6.png)

**Comment by estruyf** [comment]
Should have been fixed in version `1.2.0`. If not, feel free to open this issue or a new one.
