### ISSUE TITLE
Error when publishing md files to SharePoint

### ISSUE THREAD

**Issue by jbranders** [ValoIntranet/doctor#13]
### Error when publishing markdown file to SharePoint. 

See error below, I get an 423 error from SharePoint for check-in the file. 
Could this be resolved or do you have a workaround? 

![doctor_error](https://user-images.githubusercontent.com/16958349/102546386-d9ab3100-40b7-11eb-9bbe-987c6666f9af.png)

**Comment by estruyf** [comment]
Related to #12 - working on Windows support.

**Comment by estruyf** [comment]
Just released the first beta with Windows support, feel free to test it out by installing: `npm i @valo/doctor@next -g`.

**Comment by estruyf** [comment]
Should have been fixed in version `1.2.0`. If not, feel free to open this issue or a new one.
