### ISSUE TITLE
Draft is a required property to have page published on site

### ISSUE THREAD

**Issue by mheptinstall** [ValoIntranet/doctor#25]
If the `draft` property is not present and set to `false` in the front matter the page is published as a draft by default.

The property is listed as optional, my assumption was that if the property is not present then the page would be published on the site.

![image](https://user-images.githubusercontent.com/10913145/103438042-51d03580-4c26-11eb-9fa9-c913046a0101.png)

**Comment by estruyf** [comment]
Thanks @mheptinstall for the feedback. This is the initial approach we took, but can always be changed.

**Comment by estruyf** [comment]
This will be released in `1.4.0`.
