### ISSUE TITLE
Add support for comments property

### ISSUE THREAD

**Issue by mheptinstall** [ValoIntranet/doctor#27]
Allow page comments to be enabled/disabled.

This could be done globally in doctor.json and/or a front matter page property.

**Comment by estruyf** [comment]
Again great suggestion to enhance Doctor.

**Comment by estruyf** [comment]
Will be released in `1.4.0`

**Comment by pkskelly** [comment]
Just ran into this same situation and was about to open a new Issue.  Looking forward to this feature.

**Comment by estruyf** [comment]
The feature is available on `page` level by setting the `comments` property to `false` if you want to turn these off. Setting this on global level is something `doctor` still needs to still support.
