### ISSUE TITLE
cleanStart only executes with --confirm option

### ISSUE THREAD

**Issue by mheptinstall** [ValoIntranet/doctor#28]
Clean up only executes when I use `doctor publish --cleanStart --confirm`

If I use `doctor publish --cleanStart` I get the prompt:

> Are you sure you want to clean up all pages and assets? (y/N)

I press `y` and the publish does not perform a clean up.

**Comment by estruyf** [comment]
Releasing this in `1.3.1` right now. Thanks @mheptinstall for the fix!
