### ISSUE TITLE
Add support for creating pages using page templates.

### ISSUE THREAD

**Issue by P3N-101** [ValoIntranet/doctor#33]
Would be really useful to be able to select a page template for the documentation pages, I have templates with exisiting webparts that can provide a toc or page menu and would be really great to use these rather than have to edit them after creation.

**Comment by estruyf** [comment]
Thanks @P3N-101 this would be a great enhancement to the tool.

**Comment by estruyf** [comment]
Implementation of this functionality can start once the following issue is closed: https://github.com/pnp/cli-microsoft365/issues/2065

**Comment by estruyf** [comment]
Support for this has been added to the `1.5.0` beta. Feel free to give it a try. The sample options page contains a template configuration: https://github.com/ValoIntranet/doctor-sample/blob/main/src/doctor/options.md - `template: PageTemplate`. Where `PageTemplate` is the name of the template to use.
