### ISSUE TITLE
Error updating Navigation

### ISSUE THREAD

**Issue by P3N-101** [ValoIntranet/doctor#39]
Getting this error on both 1.4.0 and 1.5.0 beta

× Updating navigation
    → Error: 'https://tenant.sharepoint.com/sites/DocsTest' is not a valid SharePoint Online site URL
 ERROR:  Command failed: localm365 spo navigation node list --webUrl 'https://tenant.sharepoint.com/sites/DocsTest' --location TopNavigationBar -o json
Error: 'https://inspectplus.sharepoint.com/sites/DocsTest' is not a valid SharePoint Online site URL

**Comment by P3N-101** [comment]
If I run the same command directly in the console, ie localm365 spo navigation node list --webUrl 'https://tenant.sharepoint.com/sites/DocsTest' --location TopNavigationBar -o json

It works fine... and I get the json response

**Comment by estruyf** [comment]
What version do you have locally installed @P3N-101?

**Comment by estruyf** [comment]
Seems that this error is only returned in the CLI for Microsoft 365 on the SPO Command argument validation. The only thing I can think of is a difference in a local version.

**Comment by estruyf** [comment]
Seems I found the issue. There was a single quote used in the URL and this causes issues on Windows. Released a new beta version. Feel free to give it a try.

**Comment by P3N-101** [comment]
localm365 --version v3.6.0-beta.3066a8 
m365 --version v3.5.0

It seems to be the Menu element of the Doctor.json file that causes the error, without that section it runs without error but still doesnt update the navigation.   

I was testing with a comms site thinking the TopNavigationBar was the correct element, nope it returns nothing but QuickLaunch does return so changed it to QuickLaunch but still the same error

**Comment by P3N-101** [comment]
Just ran the new beta this is now fixed awesome thanks... I have another one to raise though
