### ISSUE TITLE
Only the first image on a page is

### ISSUE THREAD

**Issue by P3N-101** [ValoIntranet/doctor#40]
On Windows only the first Image on each page is uploaded and referenced, no other images get uploaded.

**Comment by estruyf** [comment]
Would you be able to provide some sample content? That way I can add it to the test as well.

**Comment by P3N-101** [comment]
I have attached the  I am testing...

[testing-docs.zip](https://github.com/ValoIntranet/doctor/files/5933976/testing-docs.zip)

**Comment by estruyf** [comment]
Found the issue and should have been fixed in the latest `1.5.0` beta.

**Comment by P3N-101** [comment]
Yep all fixed for me thanks...
